workflows:
  ios-release:
    name: iOS Release
    environment:
      groups:
        - new
      vars:
        XCODE_PROJECT: "HotNote.xcodeproj"
        XCODE_SCHEME: "HotNote"
        BUNDLE_ID: "com.PhlpJiseph.Films"
        APP_STORE_APPLE_ID: "123456789"
        TEAM_ID: "Y4JKCJ5SG3"
    scripts:
      - name: Set up keychain and provisioning profiles
        script: |
          keychain initialize
          
          # Install App Store Connect private key
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" > /tmp/auth_key.p8
          
          # Install certificates and provisioning profiles
          app-store-connect fetch-signing-files \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_ID" \
            --private-key @file:/tmp/auth_key.p8 \
            "$BUNDLE_ID" \
            --type IOS_APP_STORE
          
          xcode-project use-profiles
          
      - name: Build and archive
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      app_store_connect:
        # Авторизация в App Store Connect
        auth: integration
        
        # Настройки публикации
        submit_to_app_store: true
        
        # Идентификатор приложения в App Store Connect
        application_id: $APP_STORE_APPLE_ID

# Настройки триггеров
triggering:
  events:
    - push
    - tag
    - pull_request
  branch_patterns:
    - pattern: main
      include: true
      source: true
    - pattern: release/*
      include: true
      source: true

# Настройки окружения
environment:
  xcode: 15.0 # Укажите нужную версию Xcode
