workflows:
  ios-hotnote-release:
    name: HotNote iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.PhlpJiseph.Films"
      vars:
        XCODE_PROJECT: "HotNote.xcodeproj"
        XCODE_SCHEME: "HotNote"
        BUNDLE_ID: "com.PhlpJiseph.Films"
        APP_STORE_APPLE_ID: "123456789"
        APP_STORE_CONNECT_ISSUER_ID: "76f522ce-5da9-4149-b26e-3ae60fc2a824"
        APP_STORE_CONNECT_KEY_ID: "WBP2ND8WH6"
        APP_STORE_CONNECT_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgK1Cgd7kcYlr03SDggSIdf++kFAk0GS67WNiVutpT3h6gCgYIKoZIzj0DAQehRANCAAS+QTxZxRTRFdg6XpqYdgBbQXKAWNg+LrEIN+lyfc92v57Gntj8yY6gfucGjHwA7+A3iTwgGdE5tMpaJuqhiQWD-----END PRIVATE KEY-----"
        TEAM_ID: "Y4JKCJ5SG3"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up provisioning profiles
        script: xcode-project use-profiles
      - name: Increment build number
        script: | 
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" || echo 0)
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        expire_build_submitted_for_review: false
        # Раскомментируйте и добавьте названия бета-групп при необходимости
        # beta_groups:
        #   - "Internal Testers"
        #   - "External Testers"
        submit_to_app_store: false
      email:
        recipients:
          - your-email@example.com # ЗАМЕНИТЕ на ваш email
        notify:
          success: true
          failure: true
